# Generated by Django 4.1.1 on 2022-09-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Suplemento",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=255)),
                ("marca", models.CharField(max_length=80)),
                ("categoria", models.CharField(max_length=80)),
                ("preco", models.IntegerField()),
            ],
        ),
    ]
